### PR TITLE
implement basic access log

### LINKED ISSUE #71: express access log as json

### PR DESCRIPTION
**Pull request by adamtulinius**
fixes #71

### CODE REVIEW

**Comment by adamtulinius** [comment]
@rasmuserik should `app.use(expressLoggers.logger);` be removed from app.js?

**Comment by rasmuserik** [comment]
I think so, yes. And then probably also remove it from package.json.
(assuming the production setup just takes the log from stdout).

**Comment by adamtulinius** [comment]
I'll remove it shortly.

**Comment by adamtulinius** [comment]
I can't remove the dbc-node-logger dependency, since we still use the error logger from there.

**Comment by rasmuserik** [comment]
Will merge as soon as conflicts are resolved :)

**Pull request merged**
