### PR TITLE
added function to wrap context

### PR DESCRIPTION
**Pull request by FlashGordon**

### CODE REVIEW

**Comment by rasmuserik** [comment]
Looks good, maybe we should put this as a method in caller.js, instead of a new class in util.js

**Comment by cboesgaard** [comment]
Yes, it would reduce code if this was somehow part of the context.

**Comment by FlashGordon** [comment]
Ill move it

**Comment by rasmuserik** [comment]
I was imagining it less general as a method on the caller, i.e.:
```javascript
class Context { // already in the file
 //...
    get(key) {
      let keys = key.split('.');
      let value = keys.reduce((o, name) => 
                            { return o && o[name]; }, this.data);
      return value;
  };
}
```

**Comment by rasmuserik** [comment]
Could also be:
```javascript
return key.split('.').reduce((o, name) => o && o[name], this.data);
```

**Pull request merged**
